name: Automated Testing Workflow

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python Version for the Virtual Environment'
        required: true
        default: '3.9'
      tests_folder:
        description: 'Location of the Test Folder'
        required: true
        default: 'tests'
      requirements_file:
        description: 'Path to requirement.txt file'
        required: true
        default: 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install -r ${{ inputs.requirements_file }}
          pip install -r ${{ inputs.requirements_file }}
      - name: Run Tests
        run: pytest ${{ inputs.tests_folder }}
